# Generated by Django 6.0.6 on 2026-06-25 17:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.CreateModel(
            name='Savant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('biographie', models.TextField(blank=True, null=True, verbose_name='Biographie')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_savants/', verbose_name='Photo de profil')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Savant',
                'verbose_name_plural': 'Savants',
            },
        ),
        migrations.CreateModel(
            name='Preche',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255, verbose_name='Titre du prêche')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Résumé')),
                ('audio_fichier', models.FileField(upload_to='audios_preches/', verbose_name='Fichier Audio (MP3)')),
                ('duree_secondes', models.IntegerField(blank=True, null=True, verbose_name='Durée (en secondes)')),
                ('taille_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (en octets)')),
                ('langue', models.CharField(choices=[('Dendi', 'Dendi'), ('Bariba', 'Bariba'), ('Haoussa', 'Haoussa'), ('Français', 'Français'), ('Autre', 'Autre')], default='Dendi', max_length=50, verbose_name='Langue du prêche')),
                ('date_enregistrement', models.DateField(blank=True, null=True, verbose_name="Date de l'enregistrement")),
                ('est_public', models.BooleanField(default=True, verbose_name="Visible sur l'application")),
                ('telechargements_count', models.IntegerField(default=0, verbose_name='Nombre de téléchargements')),
                ('ecoutes_count', models.IntegerField(default=0, verbose_name="Nombre d'écoutes")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='preches', to='api_core.categorie', verbose_name='Catégorie')),
                ('savant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preches', to='api_core.savant', verbose_name='Savant')),
            ],
            options={
                'verbose_name': 'Prêche',
                'verbose_name_plural': 'Prêches',
                'ordering': ['-date_creation'],
            },
        ),
    ]
